param(
    [string]$InputPath = (Join-Path $PSScriptRoot "..\data\world.json"),
    [string]$OutputPath = (Join-Path $PSScriptRoot "..\src\generated\world-data.js"),
    [string]$PassagesPath = (Join-Path $PSScriptRoot "..\src\generated\world-passages.twee")
)

$ErrorActionPreference = "Stop"
$resolvedInput = [System.IO.Path]::GetFullPath($InputPath)
$resolvedOutput = [System.IO.Path]::GetFullPath($OutputPath)
$resolvedPassages = [System.IO.Path]::GetFullPath($PassagesPath)

if (-not (Test-Path -LiteralPath $resolvedInput -PathType Leaf)) {
    throw "Authoritative world data was not found: $resolvedInput"
}

$document = Get-Content -Raw -LiteralPath $resolvedInput | ConvertFrom-Json
if ($document.schemaVersion -ne 1) {
    throw "Unsupported world schemaVersion. Expected 1."
}
if ($null -eq $document.locations) {
    throw "world.json must contain a locations object."
}

$json = $document | ConvertTo-Json -Depth 100
$json = $json -replace '</', '<\/'
$javascript = @"
/* Generated from data/world.json. Do not edit this file directly. */
(function () {
    "use strict";
    setup.GeneratedWorldData = $json;
}());
"@

$outputDirectory = Split-Path -Parent $resolvedOutput
New-Item -ItemType Directory -Force -Path $outputDirectory | Out-Null
[System.IO.File]::WriteAllText($resolvedOutput, $javascript, [System.Text.UTF8Encoding]::new($false))
$passages = New-Object System.Collections.Generic.List[string]
foreach ($locationProperty in $document.locations.PSObject.Properties) {
    $passage = [string]$locationProperty.Value.passage
    if ([string]::IsNullOrWhiteSpace($passage) -or $passage -match '[\r\n\[\]]') {
        throw "Location $($locationProperty.Name) has an invalid Twine passage name."
    }
    $passages.Add(":: $passage`r`n<div id=`"location-view`"></div>`r`n")
}
[System.IO.File]::WriteAllText($resolvedPassages, ($passages -join "`r`n"), [System.Text.UTF8Encoding]::new($false))
Write-Host "Generated $resolvedOutput"
Write-Host "Generated $resolvedPassages"
